### ISSUE TITLE
[RFC] Template hygiene - Capturing undeclared identifier in templates

### ISSUE THREAD

**Issue by mratsim** [nim-lang/RFCs#52] opened 2018-07-05 07:44 UTC
I feel that the following should require a `{.dirty.}` pragma to compile as x is declared nowhere in the template.

```Nim
template foo(): int =
  x + 1

proc bar(x: int): int =
  foo()

echo bar(2)
```

Use case: when refactoring complex templates used for proc implementations it is very easy to use:
```Nim
template foo2() =
  # ... complex template
  result += 1
```

instead of

```Nim
template foo3(result: var int) =
  # ... complex template
  result += 1
```

A dirty pragma makes the intent explicit.

**Comment by Araq** [comment] 2019-01-04 17:12
Duplicate of https://github.com/nim-lang/RFCs/issues/78

**Closed by Araq** 2019-01-04 17:12 UTC
