### ISSUE TITLE
Deprecate TaintedString

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/RFCs#287] opened 2020-11-20 13:36 UTC
Deprecate TaintedString
https://github.com/nim-lang/Nim/pull/15423

**Comment by disruptek** [comment] 2020-11-20 18:15
Maybe type a few words about why you think this is a useful change?

**Comment by hlaaftana** [comment] 2020-11-21 18:48
#24 for discussion from 2017

**Comment by Araq** [comment] 2020-12-10 09:36
Duplicate of #24, dubious, unknown voters.

**Closed by Araq** 2020-12-10 09:36 UTC
